/*
 Copyright 2014 Digipolitan. All rights reserved.
 
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
 
 1. Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.
 
 2. Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 
 3. Neither the name of the owner nor the names of its contributors may be used
 to endorse or promote products derived from this software without specific prior written permission.
 
 THIS SOFTWARE IS PROVIDED BY DIGIPOLITAN ''AS IS'' AND ANY EXPRESS OR
 IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
 EVENT SHALL DIGIPOLITAN BE LIABLE FOR ANY DIRECT,
 INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#import <DGFoundation/DGFICancelableTask.h>
#import <DGFoundation/DGFTaskResultBlock.h>

@protocol DGNIOAuthConfiguration;
@class DGNOAuthToken;
@class NSURL;

/**
 * Interface describing an OAuth service
 * @author Benoit BRIATTE http://www.digipolitan.com
 * @version 1.0
 * @date October 2014
 */
@protocol DGNIOAuthService <DGFICancelableTask>
@required

/**
 * Must retrieve the configuration
 * @return The OAuth configuration of the service
 */
- (id<DGNIOAuthConfiguration>) configuration;

/**
 * Must retrieve the request token
 * @param resultBlock The result block
 */
- (void) requestTokenWithResultBlock:(DGFTaskResultBlock /** DGNOAuthToken */) resultBlock;

/**
 * Must retrieve the request token using a callback URL
 * @param callbackURL Your callback URL @see DGNCallbackManager
 * @param resultBlock The result block
 */
- (void) requestTokenWithCallbackURL:(NSURL*) callbackURL resultBlock:(DGFTaskResultBlock /** DGNOAuthToken */) resultBlock;

/**
 * Must build the authorize URL using the given token
 * @param requestToken The request token generated by the requetToken method
 * @return An authorize URL for the end-user
 */
- (NSURL*) authorizeURLWithRequestToken:(DGNOAuthToken*) requestToken;

/**
 * Must generate the access token using the given response URL
 * @param responseURL The responseURL comes from an user action in the authorize URL (in a webview).
 * @param resultBlock The result block
 */
- (void) accessTokenWithAuthorizeResponseURL:(NSURL*)responseURL resultBlock:(DGFTaskResultBlock /** DGNOAuthToken */) resultBlock;

@end
